### ISSUE TITLE
handling of rotations

### ISSUE THREAD

**Issue by tnowotny** [jamesturner246/vicon-dvs-projection#2]
I think we have a few inconsistencies here that we need to address:
1. In:
https://github.com/jamesturner246/vicon-dvs-projection/blob/2fcce771e088bb62116cc1492c636db0972a16e5/projection.py#L207
you seem to be converting into degrees rather than radians. I think that is probably not a good idea as the normal trigonometric functions expect radians. All the camera rotations are in radians.

**Comment by tnowotny** [comment]
2. In:
https://github.com/jamesturner246/vicon-dvs-projection/blob/2fcce771e088bb62116cc1492c636db0972a16e5/projection.py#L501
It looks like you are just adding the Euler angles from the Vicon system to the Euler angles from the camera calibration. I am fairly certain this is not correct. I can't find anything specific about this so I will calculate the safe version where one converts both sets of Euler angles into the correct rotation matrix, multiplies those matrices and then extracts Euler angles from the resulting rotation matrix. It's going to be a bit of a nightmare with all the transposing and changed order the "row vector approach" is bringing to us but will provide the solution soon.
In the meantime I also wonder whether the ```rotation``` is actually in degrees here and ```dv_space_euler_angles[i]``` in radians?
Also, do we know that the Vicon system is using the same traditional rotation matrices for the Euler angle definition that we've been using?

**Comment by jamesturner246** [comment]
fixed in main
